---
name: Setup Lint Test Scan

on:
  push:
    branches: [main, dev, staging]
  pull_request:
    branches: [main, dev, staging]
  release:
    types: [published]
  schedule:
    - cron: "0 2 * * 1" # Weekly dependency check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: npm run format

      - name: Run lint
        run: npm run lint

        #- name: Run tests
        # run: npm test

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: javascript,typescript
        continue-on-error: true

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        continue-on-error: true

      - name: Run Semgrep scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          output: semgrep.sarif
        continue-on-error: true

      # or (need SONAR_PROJECT_KEY, SONAR_ORGANIZATION, SONAR_TOKEN)
      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   with:
      #     projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
      #     organization: ${{ secrets.SONAR_ORGANIZATION }}
      #     token: ${{ secrets.SONAR_TOKEN }}

      - name: Run Trivy security scan (source)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"
        continue-on-error: true

      - name: Upload Trivy SARIF results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-results
          path: trivy-results.sarif

      - name: Upload Semgrep SARIF results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep.sarif
